### ISSUE TITLE
[Chili-Rezept] Knoblauch fehlt in der Zubereitungsbeschreibung

### ISSUE THREAD

**Issue by VanillaChief** [roddi/WinkenschuerfelRecipes#1]
War verwirrt, wann der Knoblauch ins Spiel kommt. Habe mit Textsuche nochmal bestätigt, dass er in der Beschreibung der Zubereitung nicht mehr erwähnt wird. Wird er separat gereicht? :D

**Comment by roddi** [comment]
Hehe, ein Bugreport für ein Kochrezept! Danke dafür. Ich brate den Knoblauch am Anfang mit an.
